[FIX] web: prevent error when split an expense
Currently, an error occurs when users press the data-hotkey 'ALT + Q' to split
expense and any expense is not available in the split expense line.

Step to produce:

- Install the 'hr_expense' module.
- Create an expense, add a category, and click on the 'Split Expense' button.
- Delete all expenses from the split expense line, and press the data-hotkey
'ALT + Q' to click on the 'Split Expense' button to split expenses.

IndexError: tuple index out of range

This occurs because the system attempts to access the first expense from the
split expense line [1], but expenses are not available.

Link [1]: https://github.com/odoo/odoo/blob/280b762e7cd1b3d9a578bbae60cbb9b137ee5ce5/addons/hr_expense/wizard/hr_expense_split_wizard.py#L36

To resolve this issue, we need to modify a selector which is passed to the
'getVisibleElements' function [2] to exclude disabled buttons, This ensures
that the data-hotkey functionality is never triggered for disabled buttons.

Link [2]: https://github.com/odoo/odoo/blob/ef17c6cdf52a40c08a54c54d834f92b25e78c8e5/addons/web/static/src/core/hotkeys/hotkey_service.js#L288

Sentry-6015854429