[FIX] stock: prevent an error when compute a display name for stock quant
Currently, an error occurs when computing a display name for stock quant.

Step to produce:

- Install the 'stock' module(without demo data).
- Go to inventory settings, enable Packages, Quality, Reception Report,
Variants, Units of Measure, Lots & Serial Numbers, Display Lots & Serial Numbers
on Delivery Slips, Expiration Dates, and Dropshipping.
- And disable the Barcode Scanner.
- Create a product and enable the Track Inventory option.
- In the product form view, click on On Hand in the breadcrumbs to navigate to
the stock quantity list view
- Create a new record to update the quantity.
- Click on the 'View' button, remove the location, and try to come back to
update quantity list view.

TypeError: sequence item 0: expected str instance, bool found

This error occurs because we compute the display name of stock quant and it is
derived from location_id, lot_id, package_id, and owner_id. If none of these
values are present in stock quant then the system tries to concate the bool
value with a string at [1] and an error occurs.

Link [1]: https://github.com/odoo/odoo/blob/e4f3b955998957279ddd153e6f72c7a53feccf64/addons/stock/models/stock_quant.py#L598-L606

To resolve this issue, Assign a default display name to stock quant if none of
values of the fields (location_id, lot_id, package_id, owner_id) are available

Sentry-6165002037