[FIX] point_of_sale: prevent nb_print as null when sync_from_ui in offline order
Currently, an exception was generated in the log when the users create
a POS order as follows:
- Open Register for Restaurant
- Stay connected to WIFI but there should not be any internet
  connection (Inspect > Network > Go offline)
- Now make orders using offline mode
- Now turn ON the internet connection and make one order
- Now close register (Traceback in terminal)

error: `invalid literal for int() with base 10: 'null'`

This is because at [1] we found `order.nb_print` as `NaN` because of
the offline order.

This commit will fix the above issue by providing a default value as
0 when `order.nb_print` is `NaN`.

[1] - https://github.com/odoo/odoo/blob/2a79d7d06d77d808cab00440bdac3c1e05c7bc1b/addons/point_of_sale/static/src/app/store/pos_store.js#L1635

sentry-6055024846