[FIX] tools: correct rounding precision in float_round
After this commit 784f151 , The `float_round()` functionality has been changed and they increases the
epsilon value from 52 to 50.

with epsilon value 50:
```
>>> from odoo.tools import float_round
>>> float_round(7802500004008,2)
7802500004008.01
```

with epsilon value 52:
```
>>> from odoo.tools import float_round
>>> float_round(7802500004008,2)
7802500004008.0
```
These differences leads to blocking the upgrade process.
During migration, When converting values to cache, calling float_round on the `7802500004008.01`, resulted in the value `7802500004008.02`.

```
Traceback (most recent call last):
  File "/tmp/tmprvn8ab3u/migrations/testing.py", line 212, in test_check
    self.check(value)
  File "/tmp/tmprvn8ab3u/migrations/stock/tests/test_on_hand_quantity.py", line 90, in check
    self.assertEqual(before_results, self.convert_check(after_results), self.message)
AssertionError: Lists differ: [[646[5654 chars]04008'], [2099, '45'], [2100, '40'], [2101, '1[18741 chars]'3']] != [[646[5654 chars]04008.02'], [2099, '45'], [2100, '40'], [2101,[18744 chars]'3']]

First differing element 421:
[2096, '7802500004008']
[2096, '7802500004008.02']

Diff is 29770 characters long. Set self.maxDiff to None to see it. : Invariant check fail
```

upg-2301744
opw-4333768